# Generated by Django 4.0.4 on 2022-05-16 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='От')),
                ('end_time', models.TimeField(verbose_name='До')),
            ],
            options={
                'verbose_name': 'Рабочее время',
                'verbose_name_plural': 'Рабочее время',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.BigIntegerField(unique=True, verbose_name='ID сотрудника')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('status', models.BooleanField(default=True, verbose_name='Статус сотрудника')),
                ('image', models.ImageField(upload_to='employee_image', verbose_name='Фото сотрудника')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Подробнее о сотруднике')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faceapp.department', verbose_name='Отдел')),
                ('working_hours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faceapp.workinghours', verbose_name='Рабочее время')),
            ],
            options={
                'verbose_name': 'Сотрудники',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('check_status', models.CharField(choices=[('checkOut', 'Выход'), ('checkIn', 'Вход')], max_length=255, verbose_name='Состояние входа')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='Вход')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Выход')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faceapp.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Посещаемость',
            },
        ),
    ]
