# Generated by Django 4.0.4 on 2022-05-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out',
        ),
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время'),
        ),
    ]
