# Generated by Django 4.0.4 on 2022-05-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0003_employee_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='person_id',
            field=models.CharField(max_length=1000, unique=True, verbose_name='ID сотрудника'),
        ),
    ]
