# Generated by Django 4.0.4 on 2022-06-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0003_alter_departmentshifttime_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('highest', 'highest'), ('lowest', 'lowest')], max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatisticsAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('highest', 'highest'), ('lowest', 'lowest')], max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatisticsWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('highest', 'highest'), ('lowest', 'lowest')], max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('percentage', models.IntegerField()),
            ],
        ),
    ]
