# Generated by Django 4.0.4 on 2022-09-24 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0004_departmentstatistics_employeestatisticsattendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Дата от')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата до')),
                ('difference', models.IntegerField(default=0, verbose_name='Количество дней')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='faceapp.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Больничный',
                'verbose_name_plural': 'Больничные',
            },
        ),
    ]
