# Generated by Django 4.0.4 on 2022-09-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0005_employeesickleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarworkingdays',
            name='cause',
            field=models.CharField(blank=True, default='---', max_length=255, null=True),
        ),
    ]
