# Generated by Django 4.0.4 on 2022-09-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0006_calendarworkingdays_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebusinesstrip',
            name='comment',
            field=models.CharField(default='---', max_length=255),
        ),
    ]
