# Generated by Django 4.0.4 on 2022-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0007_employeebusinesstrip_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesickleave',
            name='comment',
            field=models.CharField(default='---', max_length=255),
        ),
    ]
