# Generated by Django 4.0.4 on 2022-09-29 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0008_employeesickleave_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='faceapp.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='departmentshifttime',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_time_department', to='faceapp.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='card_number',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Номер карты 1c'),
        ),
        migrations.AlterField(
            model_name='employeebusinesstrip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employeesickleave',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceapp.employee', verbose_name='Сотрудник'),
        ),
    ]
