# Generated by Django 4.0.4 on 2022-10-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0010_employeebusinesstrip_status_employeesickleave_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevacation',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидание'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], max_length=255, null=True),
        ),
    ]
