# Generated by Django 4.0.4 on 2022-10-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0011_alter_employeevacation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebusinesstrip',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидание'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employeesickleave',
            name='status',
            field=models.CharField(choices=[('waiting', 'В ожидание'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], max_length=255, null=True),
        ),
    ]
