# Generated by Django 4.0.4 on 2022-10-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0012_alter_employeebusinesstrip_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatisticsworkinghours',
            name='hours',
            field=models.IntegerField(null=True),
        ),
    ]
