# Generated by Django 4.0.4 on 2022-10-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0014_alter_employee_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_at',
            field=models.DateTimeField(verbose_name='Дата присоединения'),
        ),
    ]
