# Generated by Django 4.0.4 on 2022-11-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0016_alter_employee_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentstatistics',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
