# Generated by Django 4.0.4 on 2022-11-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0018_remove_departmentstatistics_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeestatisticsattendance',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employeestatisticsattendance',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employeestatisticsworkinghours',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employeestatisticsworkinghours',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
